### ISSUE TITLE
Milestone 1 Discussion

### ISSUE THREAD

**Issue by morrismanfung** [UBC-MDS/prelim_eda_helper#1]
> Purpose: simplified feature comparison tool
> 
> Function 1: Numeric to numeric feature comparison
> - Scatter plot, trendline, highlight outliers (option)
> - Correlation
> - Number of outliers
> - P-value
> - Other important facts
> 
> Function 2: Numeric to categorical feature comparison
> - Histogram
> - Box-plot
> - Number of outliers
> - Other important facts
> 
> Function 3: Categorical to categorical feature comparison
> - Heatmap
> - Barchart
> 
> Function 4: Single feature
> - Detects feature variable type
> - Distribution plot
> - mean/ median/ std
> - Identify highly correlated features (threshold option)
> 
> 

Tasks:

- [x] Name of the project: prelim_eda_helper
- [x] Repo creation: Morris
- [x] edit CONTRIBUTORS.md : Morris
- [x] edit CONDUCT.md: Xinru
- [x] edit CONTRIBUTING.md with templates. factory_bot_rails's is pretty easy to follow: Mehwish
- [x] edit REAMD.md: Austin

write complete docstrings

- [x] Function 1 (Num vs Num): Austin
- [x] Function 2 (Num vs Cat): Morris
- [x] Function 3 (Cat vs Cat): Xinru
- [x] Function 4 (Num [its own distribution]): Mehwish

- [x] Build project boards: Morris

- [x] Build Milestones (github function): Austin

- [x] Branch protection: Morris

Note: 
1. Branch name convention: {milestone number}-{branch name} (e.g m1-function1)

- [x] Submission: Austin
