### ISSUE TITLE
Milestone 2 - To-do

### ISSUE THREAD

**Issue by morrismanfung** [UBC-MDS/prelim_eda_helper#16]
This issue is for ideas for Milestone 2. Any undone issues should be listed in another issue at the end of Milestone 2.

- [x] https://github.com/UBC-MDS/prelim_eda_helper/issues/19
- [x] https://github.com/UBC-MDS/prelim_eda_helper/issues/20
- [x] https://github.com/UBC-MDS/prelim_eda_helper/issues/21
- [x] https://github.com/UBC-MDS/prelim_eda_helper/issues/22
- [x] https://github.com/UBC-MDS/prelim_eda_helper/issues/23
- [x] https://github.com/UBC-MDS/prelim_eda_helper/issues/24
- [x] https://github.com/UBC-MDS/prelim_eda_helper/issues/25
- [x] https://github.com/UBC-MDS/prelim_eda_helper/issues/26
- [x] https://github.com/UBC-MDS/prelim_eda_helper/issues/27
- [x] https://github.com/UBC-MDS/prelim_eda_helper/issues/28
- [x] https://github.com/UBC-MDS/prelim_eda_helper/issues/29
