### ISSUE TITLE
Milestone 3 - Unresolved issue from the last milestone

### ISSUE THREAD

**Issue by morrismanfung** [UBC-MDS/prelim_eda_helper#46]
Suggested by @morrismanfung
- [ ] Consider not fixing the axis of the scatter plot to be starting from 0? 
- [ ] Adding chi-squared test to `cat_dist_heatmap`?
- [ ] Using a stacked bar chart in `cat_dist_heatmap`?
