### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/prelim_eda_helper#66]
Milestone 3 

Congratulations on finishing milestone 3 group 1!  Nice work uploading your package to PYPI! Nice work on the Tests on R and setting up your R repo!  Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.
Python Package

Nice job uploading your python package onto PyPI. 
https://pypi.org/project/prelim-eda-helper/0.1.6/

- [x] GitHub actions workflow for continuous integration and continuous deployment Badge Missing - -4 mechanics

R Package

Your R tests ran well! 
<img width="362" alt="Screenshot 2023-01-30 at 11 22 34 AM" src="https://user-images.githubusercontent.com/45893111/215592368-92cd0eed-d79f-463d-87fd-9d4f62faed24.png">

- [ ] There isn't a CONTRIBUTING.md file. THIS IS FOR THE R PACKAGE!. This group added the CONTRIBUTIONS.MD file to the Python package. This file will live in .github and it will create that folder if it does not already exist. Edit the boiler plate document this gives to to reflect your contribution strategy that your team has agreed upon.- mechanics -2. 

- [x] Some of the branches don’t mean anything for example there is a description branch and also a readme branch. These are the same things mechanics -1.

Great job, you’re at the final stretch. One milestone left :)

**Comment by MNBhat** [comment]
In discussion with Florencia

**Comment by andytai7** [comment]
Marks given back for the Pytest naming.
